# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - exe201-starotvn

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      # New step: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Exe.Starot.Api/Exe.Starot.Api.csproj

      # New step: Build the project
      - name: Build project
        run: dotnet build Exe.Starot.Api/Exe.Starot.Api.csproj --configuration Release --no-restore

      # New step: Run tests
      - name: Run tests
        run: dotnet test Exe.Starot.Api/Exe.Starot.Api.csproj --no-build --verbosity normal

      # New step: Publish project
      - name: Publish project
        run: dotnet publish Exe.Starot.Api/Exe.Starot.Api.csproj --configuration Release --output ./publish
        
      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./artifact

        # Inspect the downloaded artifact
      - name: List contents of artifact
        run: Get-ChildItem -Recurse ./artifact
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'exe201-starotvn'
          slot-name: 'Production'
          package: './artifact'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4A7B51B76E914A6BAA0C109D2771FAF8 }}
