name: Build and deploy ASP.Net Core app to Azure Web App - exe201-starotvn

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: exe201-starotvn
  AZURE_WEBAPP_PACKAGE_PATH: "./artifact/publish"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./Exe.StarotSolution.sln

      # Build the project
      - name: Build project
        run: dotnet build ./Exe.StarotSolution.sln --configuration Release --no-restore

      # Publish project
      - name: Publish project
        run: dotnet publish ./Exe.StarotSolution.sln --configuration Release --output './publish'
        
      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ./publish # Uploading the publish directory as the artifact

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: ./artifact # Downloading artifact to this location

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" # Ensure this points to the correct artifact path
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4A7B51B76E914A6BAA0C109D2771FAF8 }}
